name: Automatic changelog compile

on:
  push:
    branches:
      - 'master'
<<<<<<< HEAD:.github/workflows/autochangelog_compile.yml
    paths:
      - 'html/changelogs/**.yml'
=======
>>>>>>> f7cabf28f0... Updates token to be secret name (#12599):.github/workflows/compile_changelogs.yml
      
jobs:
  compile:
    name: Changelog compile

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
       
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '>=3.6'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYaml
    
    - name: Compiles changelog
      run: python tools/ss13_genchangelog.py html/changelog.html html/changelogs
    
    - name: Commit Artifacts
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Beat!Bot"
        git commit -m "Automatic changelog compile, [ci skip]" -a
        git pull origin master
    
    - name: Push Artifacts
      uses: ad-m/github-push-action@master
      with:
<<<<<<< HEAD:.github/workflows/autochangelog_compile.yml
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
        
=======
        github_token: ${{ secrets.ACTION_SECRET }}
>>>>>>> f7cabf28f0... Updates token to be secret name (#12599):.github/workflows/compile_changelogs.yml
