name: Automatic changelog compile

on:
  push:
    branches:
      - 'master'
    paths:
      - 'html/changelogs/**.yml'
      
jobs:
  compile:
    name: Changelog compile

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '>=3.6'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYaml
    
    - name: Compiles changelog
      run: python tools/ss13_genchangelog.py html/changelog.html html/changelogs
    
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Beat!Bot"
        git commit -m "Automatic changelog compile, [ci skip]" -a
        git pull origin master
    
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
        
